fix loading of namespaces for missing files
vinissimus/next-translate pull request #794
Opened 2022-02-23 14:47 UTC by wuifdesign

Currently if a translations file is missing no translation will be loaded. With this fix it will load all available namespaces and set translations to `{}` for missing files.

2022-02-25 13:45 UTC, aralroca requested changes
Thank you very much @wuifdesign for your contribution and welcome as a contributor 👏!

 It would be great if you could add the test of what used to crash and is now fixed, so no one will break it in the future. Thank you very much and well done. I've made a couple of comments as well. 

Thanks!

2022-02-25 13:45 UTC, aralroca commented on src/loadNamespaces.tsx
> +                .catch(() => resolve({}))
The `defaultLoader` is defined on line 44 and is just a `Promise.resolve`, in this case the catch is not necessary and we reduce the library bytes if we remove it 😁

2022-02-25 13:45 UTC, aralroca commented on src/loadNamespaces.tsx
> +          new Promise<I18nDictionary>((resolve) => {
It's not necessary to create a new `Promise`. It return already a promise.

I would change it for just:

```js
typeof conf.loadLocaleFrom === 'function'
          ? conf.loadLocaleFrom(__lang, ns).catch(() => ({}))
          : defaultLoader(__lang, ns)
```

2022-02-26 07:56 UTC, wuifdesign commented
refactored code and added tests :)

2022-05-02 20:45 UTC, aralroca approved these changes
Thanks!!! Now it's perfect!

2022-05-02 20:45 UTC, merged

2022-05-02 20:46 UTC, aralroca commented
@all-contributors please add @wuifdesign for code

2022-05-02 21:03 UTC, aralroca commented
@wuifdesign @marcesengel I prereleased [1.4.1-canary.1](https://github.com/vinissimus/next-translate/releases/tag/1.4.1-canary.1) with this fix